[project]
name = "llai-root"
version = "0.1.0"
description = "大总管根项目"
dependencies = [
    "aiosqlite>=0.22.1",
    "datasets>=5.0.0",
    "flagembedding>=1.4.0",
    "huggingface-hub>=1.16.1",
    "langchain>=1.3.11",
    "langchain-deepseek>=1.1.0",
    "peft>=0.19.1",
    "pyright>=1.1.411",
    "pytest-cov>=7.1.0",
    "scipy>=1.18.0",
    "torch>=2.12.1",
    "transformers>=5.12.1",
] 

