---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ready_node(ready_node)
	pyright_node(pyright_node)
	coder(coder)
	test_writer(test_writer)
	tester(tester)
	human_node(human_node)
	qa_node(qa_node)
	judge(judge)
	issue_manager_node(issue_manager_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> ready_node;
	coder -. &nbsp;max_attempts&nbsp; .-> human_node;
	coder -. &nbsp;success&nbsp; .-> pyright_node;
	human_node -. &nbsp;success&nbsp; .-> __end__;
	issue_manager_node -. &nbsp;dropped&nbsp; .-> __end__;
	issue_manager_node -. &nbsp;code_patcher&nbsp; .-> coder;
	issue_manager_node -. &nbsp;design_patcher&nbsp; .-> human_node;
	issue_manager_node -. &nbsp;test_code_patcher&nbsp; .-> test_writer;
	judge --> issue_manager_node;
	pyright_node -. &nbsp;code_error&nbsp; .-> coder;
	pyright_node -.-> qa_node;
	pyright_node -. &nbsp;test_code_error&nbsp; .-> test_writer;
	qa_node --> issue_manager_node;
	qa_node --> tester;
	ready_node --> coder;
	ready_node --> test_writer;
	test_writer -. &nbsp;max_attempts&nbsp; .-> human_node;
	test_writer -. &nbsp;success&nbsp; .-> pyright_node;
	tester --> judge;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
