---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ready_node(ready_node)
	coder_graph(coder_graph)
	test_coder_graph(test_coder_graph)
	test_execer_graph(test_execer_graph)
	human_node(human_node)
	qa_graph(qa_graph)
	judge_graph(judge_graph)
	spec_graph(spec_graph)
	issue_manager_node(issue_manager_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> ready_node;
	coder_graph -. &nbsp;unexpected&nbsp; .-> __end__;
	coder_graph -. &nbsp;max_attempts&nbsp; .-> human_node;
	coder_graph -. &nbsp;success&nbsp; .-> qa_graph;
	human_node -. &nbsp;success&nbsp; .-> __end__;
	issue_manager_node -. &nbsp;code_patcher&nbsp; .-> coder_graph;
	issue_manager_node -. &nbsp;design_patcher&nbsp; .-> human_node;
	issue_manager_node -. &nbsp;test_code_patcher&nbsp; .-> test_coder_graph;
	judge_graph --> issue_manager_node;
	qa_graph --> test_execer_graph;
	ready_node --> spec_graph;
	spec_graph -. &nbsp;failed&nbsp; .-> __end__;
	spec_graph -. &nbsp;go_coder&nbsp; .-> coder_graph;
	spec_graph -. &nbsp;go_test_coder&nbsp; .-> test_coder_graph;
	test_coder_graph -. &nbsp;unexpected&nbsp; .-> __end__;
	test_coder_graph -. &nbsp;max_attempts&nbsp; .-> human_node;
	test_coder_graph -. &nbsp;success&nbsp; .-> qa_graph;
	test_execer_graph --> judge_graph;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
